# Generated by Django 5.1.2 on 2024-10-20 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearanceset',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='document',
            name='predicted_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='clearanceset',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='clearance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='clearance_type',
            field=models.CharField(choices=[('admin', 'Admin Clearance'), ('academic', 'Academic'), ('financial', 'Financial'), ('library', 'Library')], max_length=20),
        ),
    ]
