# Generated by Django 5.1.2 on 2024-10-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0002_remove_clearanceset_is_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='clearance_type',
            field=models.CharField(choices=[('ADMIN', 'Admin Clearance'), ('ACADEMIC', 'Academic'), ('FINANCIAL', 'Financial'), ('LIBRARY', 'Library'), ('RESEARCH', 'Research'), ('EQUIPMENT', 'Equipment')], max_length=20),
        ),
    ]
