# Generated by Django 5.1.2 on 2024-10-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0005_document_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceset',
            name='academic_year',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='clearanceset',
            unique_together={('faculty', 'academic_year')},
        ),
    ]
