# Generated by Django 5.1.2 on 2024-10-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0006_clearanceset_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clearanceset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clearanceset',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='clearanceset',
            unique_together={('faculty', 'name')},
        ),
    ]
