# Generated by Django 5.1.2 on 2024-10-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0007_alter_clearanceset_unique_together_clearanceset_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='predicted_at',
        ),
        migrations.AlterField(
            model_name='document',
            name='predicted_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
